export const permitsInput = [
  {
    id: "permit",
    label: "Permit",
    name: "permit",
    type: "text",
    placeholder: "Permit",
    required: true,
  },
  {
    id: "form",
    label: "Form",
    name: "form",
    type: "text",
    placeholder: "Form",
    required: true,
  },
  {
    id: "renewalProcess",
    label: "Renewal Process",
    name: "renewalProcess",
    type: "text",
    placeholder: "Renewal Process",
    required: true,
  },
  {
    id: "renewalDuration",
    label: "Renewal Duration",
    name: "renewalDuration",
    type: "text",
    placeholder: "Renewal Duration",
    required: true,
  },
  {
    id: "renewalDeadline",
    label: "Renewal Deadline",
    name: "renewalDeadline",
    type: "date",
    placeholder: "Renewal Deadline",
    required: true,
  },
  {
    id: "expirationDate",
    label: "Expiration Date",
    name: "expirationDate",
    type: "date",
    placeholder: "Expiration Date",
    required: true,
  },
  {
    id: "contactInfo",
    label: "Contact Info",
    name: "contactInfo",
    type: "text",
    placeholder: "Contact Info",
    required: true,
  },
  {
    id: "notes",
    label: "Notes",
    name: "notes",
    type: "text",
    placeholder: "Notes",
    required: true,
  },
  {
    id: "notifyAdmin",
    label: "Notify Admin",
    name: "notifyAdmin",
    selectOpts: [
      { value: "admin 1", name: "admin 1" },
      { value: "admin 2", name: "admin 2" },
      { value: "admin 3", name: "admin 3" },
      { value: "admin 4", name: "admin 4" },
      { value: "admin 5", name: "admin 5" },
    ],
    required: true,
  },
  {
    id: "alertPriorDeadline",
    label: "Alert Prior Deadline (Days)",
    name: "alertPriorDeadline",
    type: "number",
    placeholder: "Alert Prior Deadline (Days)",
    required: true,
  },
];
