export const productionInputs = [
  {
    id: "status",
    label: "Status",
    name: "status",
    required: true,
    selectOpts: [
      { value: "Machining", name: "Machining" },
      { value: "Building", name: "Building" },
      { value: "Coating", name: "Coating" },
      { value: "Assembly", name: "Assembly" },
    ],
  },
  {
    id: "batch",
    label: "Batch",
    name: "batch",
    type: "text",
    placeholder: "Batch",
    required: true,
  },
  {
    id: "serialNumber",
    label: "Serial Number",
    name: "serialNumber",
    type: "text",
    placeholder: "Serial Number",
    required: true,
  },
  {
    id: "quantity",
    label: "Quantity",
    name: "quantity",
    type: "text",
    placeholder: "Quantity",
    required: true,
  },
  {
    id: "rangeMin",
    label: "Min",
    name: "range.min",
    type: "number",
    placeholder: "Min",
    required: true,
  },
  {
    id: "rangeMax",
    label: "Max",
    name: "range.max",
    type: "number",
    placeholder: "Max",
    required: true,
  },
  {
    id: "missing",
    label: "Missing",
    name: "missing",
    type: "text",
    placeholder: "Missing",
    required: true,
  },
];
