import { vendorData } from "../../mock/vendor";

export const purchaseInputs = [
  {
    id: "date",
    name: "date",
    label: "Date",
    type: "date",
    placeholder: "Date",
    required: true,
  },
  {
    id: "orderNumber",
    name: "orderNumber",
    label: "Order Number",
    type: "text",
    placeholder: "Order Number",
    required: true,
  },
  {
    id: "vendor",
    name: "vendor",
    label: "Vendor",
    selectOpts: vendorData,
    required: true,
  },
  {
    id: "substituteVendor",
    name: "substituteVendor",
    label: "Substitute Vendor",
    selectOpts: vendorData,
  },
  {
    id: "item",
    name: "item",
    label: "Item",
    type: "text",
    placeholder: "Item",
    required: true,
  },
  {
    id: "size",
    name: "size",
    label: "Size",
    type: "text",
    placeholder: "Size",
    required: true,
  },
  {
    id: "quantity",
    name: "quantity",
    label: "Quantity",
    type: "text",
    placeholder: "Quantity",
    required: true,
  },
  {
    id: "price",
    name: "price",
    label: "Price",
    type: "number",
    placeholder: "Price",
    required: true,
  },
  {
    id: "totalAmount",
    name: "totalAmount",
    label: "Total Amount",
    type: "text",
    placeholder: "Total Amount",
    required: true,
  },
  {
    id: "depositedAmount",
    name: "depositedAmount",
    label: "Deposited Amount",
    type: "text",
    placeholder: "Deposited Amount",
    required: true,
  },
  {
    id: "status",
    name: "status",
    label: "Status",
    selectOpts: [
      { value: "open", name: "Open" },
      { value: "close", name: "Close" },
    ],
    required: true,
  },
  {
    id: "updatedAt",
    name: "updatedAt",
    label: "Updated At",
    type: "date",
    placeholder: "Updated At",
    required: true,
  },
];
