name: Close Issues on Branch Merge

on:
  push:
    branches:
      - main # Define your main branch here
      - client
      - server

jobs:
  close-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is Merged
        id: pr-check
        uses: srt32/is-pr-merged@v1
        with:
          token: ${{ secrets.ISSUE_CLOSE_TOKEN }}
          prBranch: ${{ github.event.pull_request.head.ref }}
          targetBranch: ${{ github.event.pull_request.base.ref }}

      - name: Close Linked Issues
        if: steps.pr-check.outputs.merged == 'true'
        run: |
          gh issue list -L linked -R ${{ github.repository }} | \
            grep -Eo '#[0-9]+' | \
            xargs -I {} gh issue close {}
