export const employeeInfoInputs = [
  {
    id: "name",
    label: "Name",
    name: "name",
    type: "text",
    placeholder: "Name",
    required: true,
    pattern: "[A-Za-z ]{1,}",
    errorMessage: "Name should contain only letters!",
  },
  {
    id: "phone",
    label: "Phone",
    name: "phone",
    type: "tel",
    placeholder: "Phone",
    required: true,
    pattern: "[0-9]{10}",
    errorMessage: "Phone number should be 10 digits!",
  },
  {
    id: "workEmail",
    label: "Work Email",
    name: "workEmail",
    type: "email",
    placeholder: "Email",
    required: true,
    pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,}$",
    errorMessage: "Please enter a valid email!",
  },
  {
    id: "personalEmail",
    label: "Personal Email",
    name: "personalEmail",
    type: "email",
    placeholder: "Email",
    required: true,
    pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,}$",
    errorMessage: "Please enter a valid email!",
  },

  {
    id: "DOB",
    label: "Date of Birth",
    name: "DOB",
    type: "date",
    placeholder: "Date of Birth",
    required: true,
  },
  {
    id: "address",
    label: "Address",
    name: "address",
    type: "text",
    placeholder: "Address",
    required: true,
  },

  {
    id: "role",
    label: "Role",
    name: "role",
    selectOpts: [
      { value: "admin", name: "Admin" },
      { value: "employee", name: "Employee" },
    ],
  },
  {
    id: "position",
    label: "Position",
    name: "position",
    type: "text",
    placeholder: "Position",
    required: true,
  },
  {
    id: "emergencyContactName",
    label: "Emergency Contact Name",
    name: "emergencyContact.name",
    type: "text",
    placeholder: "Emergency Contact Name",
    required: true,
    pattern: "[A-Za-z ]{1,}",
    errorMessage: "Name should contain only letters!",
  },
  {
    id: "emergencyContactPhone",
    label: "Emergency Contact Phone",
    name: "emergencyContact.phone",
    type: "tel",
    placeholder: "Emergency Contact Phone",
    required: true,
    pattern: "[0-9]{10}",
    errorMessage: "Phone number should be 10 digits!",
  },
  {
    id: "startDate",
    label: "Start Date",
    name: "startDate",
    type: "date",
    placeholder: "Start Date",
    required: true,
  },
  {
    id: "endDate",
    label: "End Date",
    name: "endDate",
    type: "date",
    placeholder: "End Date",
    required: true,
  },
  {
    id: "onboardingComplete",
    label: "Onboarding Complete",
    name: "onboardingComplete",
    selectOpts: [
      { value: "true", name: "Yes" },
      { value: "false", name: "No" },
    ],
  },
  {
    id: "password",
    label: "Password",
    name: "password",
    type: "password",
    placeholder: "Password",
    required: true,
    value: "RT12345!",
    pattern: `^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{8,20}$`,
    errorMessage:
      "Password should be 8-20 characters and include at least 1 letter, 1 number and 1 special character!",
  },
];
