export const itemsInputs = [
  {
    id: "item",
    name: "item",
    label: "Item",
    type: "text",
    placeholder: "Item",
    required: true,
  },
  {
    id: "size",
    name: "size",
    label: "Size",
    type: "text",
    placeholder: "Size",
    required: true,
  },
  {
    id: "quantity",
    name: "quantity",
    label: "Quantity",
    type: "text",
    placeholder: "Quantity",
    required: true,
    errorMessage: "Please enter a valid phone number",
  },
  {
    id: "price",
    name: "price",
    label: "Price",
    type: "number",
    placeholder: "Price",
    required: true,
  },
  {
    id: "total amount",
    name: "total amount",
    label: "Total Amount",
    type: "number",
    placeholder: "Total Amount",
    required: true,
    pattern: "[0-9]{10}",
    errorMessage: "Please enter a valid phone number",
  },
  {
    id: "deposit amount",
    name: "deposit amount",
    label: "Deposit Amount",
    type: "number",
    placeholder: "Deposit Amount",
    required: true,
    pattern: "[0-9]{10}",
    errorMessage: "Please enter a valid phone number",
  },
  {
    id: "delivered items",
    name: "delivered items",
    label: "Delivered Items",
    type: "number",
    placeholder: "Delivered Items",
    required: true,
    pattern: "[0-9]{10}",
  },
  {
    id: "vendor",
    name: "vendor",
    label: "Vendor",
    selectOpts: [
      { value: "id-1", name: "Vendor 1" },
      { value: "id-2", name: "Vendor 2" },
      { value: "id-3", name: "Vendor 3" },
      { value: "id-4", name: "Vendor 4" },
      { value: "id-5", name: "Vendor 5" },
    ],
  },
  {
    id: "date",
    name: "date",
    label: "Date",
    type: "date",
    placeholder: "Date",
    required: true,
    pattern: "",
    errorMessage: "",
  },

  {
    id: "substitute vendor",
    name: "substitute vendor",
    label: "Substitute Vendor",
    selectOpts: [
      { value: "id-1", name: "Sub-Vendor 1" },
      { value: "id-2", name: "Sub-Vendor 2" },
      { value: "id-3", name: "Sub-Vendor 3" },
      { value: "id-4", name: "Sub-Vendor 4" },
      { value: "id-5", name: "Sub-Vendor 5" },
    ],
  },
  {
    id: "needed",
    name: "needed",
    label: "Needed",
    defaultValue: "Select",
    selectOpts: [
      { value: "ASAP", name: "ASAP" },
      { value: "Soon", name: "Soon" },
    ],
  },
];
