export const maintenanceInputs = [
  {
    id: "machine",
    label: "Machine",
    name: "machine",
    type: "text",
    required: true,
  },
  {
    id: "condition",
    label: "Condition",
    name: "condition",
    selectOpts: [
      { value: "good", name: "Good" },
      { value: "fair", name: "Fair" },
      { value: "poor", name: "Poor" },
      { value: "bad", name: "Bad" },
    ],
    required: true,
  },
  {
    id: "location",
    label: "Location",
    name: "location",
    type: "text",
    required: true,
  },
  {
    id: "assignedTo",
    label: "Assigned To",
    name: "assignedTo",
    selectOpts: [
      { value: "john", name: "John" },
      { value: "rachel", name: "Rachel" },
      { value: "janai", name: "Janai" },
      { value: "asif", name: "Asif" },
    ],
    required: true,
  },
  {
    id: "lastMaintenanceDate",
    label: "Last Maintenance Date",
    name: "lastMaintenanceDate",
    type: "date",
    required: true,
  },
  {
    id: "maintenanceInterval",
    label: "Maintenance Interval",
    name: "maintenanceInterval",
    type: "number",
    required: true,
  },
  {
    id: "notes",
    label: "Notes",
    name: "notes",
    type: "text",
    required: true,
  },
];
